# Generated by Django 4.0.4 on 2022-08-08 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 13, 48, 41, 937167)),
        ),
    ]
